### ISSUE TITLE
Allow overriding variables

### ISSUE THREAD

**Issue by NicoHaase** [ghost-inspector/ghost-inspector-jenkins-plugin#1]
In our GI tests, we use some variables to switch between different environments of a test suite. It would be nice if the Jenkins plugin would allow us to override these variables, as it is possible through the web interface and the manual API calls

**Comment by justinklemm** [comment]
@NicoHaase Apologies for the delay in following up. Thanks for suggesting this! We're evaluating this feature and seeing if it's something we can easily implement. We'll follow up on this thread shortly.

**Comment by justinklemm** [comment]
@NicoHaase We've updated the plugin to support this. Try grabbing the latest copy here: https://ghostinspectortest.com/assets/ghost-inspector.hpi. You'll need to upload it to Jenkins and let Jenkins restart. There's now a field where custom API parameters can be specified. (This update also allows you to include environment variables in your plugin settings using `$VAR_NAME` syntax).
